### ISSUE TITLE
use lightline-ale error

### ISSUE THREAD

**Issue by Hello-Linux** [maximbaz/lightline-ale#13] opened 2018-10-16 05:36 UTC
when I install this plugin and my vim show this error
![error](https://user-images.githubusercontent.com/17851645/46994802-88eec500-d148-11e8-9654-63c7cb866141.png)

**Comment by maximbaz** [comment] 2018-10-16 17:19
Install lightline plugin 🙂 Duplicate of #7

**Closed by maximbaz** 2018-10-16 17:19 UTC
